### ISSUE TITLE
runs page: date filter box is not aligned with other widgets 

### ISSUE THREAD

**Issue by kamoltat** [zmc/pulpito-ng#4]
We should align the date filter box to other widgets

![image](https://github.com/zmc/pulpito-ng/assets/22287000/fab2ea4e-c608-4500-8e2b-849baf2fff65)

**Comment by zmc** [comment]
We fixed this in https://github.com/ceph/pulpito-ng/commit/eb1bc8f222fa9bd8777b05e958d4752afedd931c
